// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyN1GuWumPgqhPQW-BY7666GGRmJidMvs',
    appId: '1:206891758660:web:ca52bb037750852655b811',
    messagingSenderId: '206891758660',
    projectId: 'wholesellexapplication-542be',
    authDomain: 'wholesellexapplication-542be.firebaseapp.com',
    storageBucket: 'wholesellexapplication-542be.firebasestorage.app',
    measurementId: 'G-5QL018P1JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKduvd2vI74fq61OONwsE2dZf06fk5tp0',
    appId: '1:206891758660:android:669fce942921593455b811',
    messagingSenderId: '206891758660',
    projectId: 'wholesellexapplication-542be',
    storageBucket: 'wholesellexapplication-542be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLtU3YozcbhpRiGNkZvpgTpEW9YXkq3Lo',
    appId: '1:206891758660:ios:adce6dba2f111b9955b811',
    messagingSenderId: '206891758660',
    projectId: 'wholesellexapplication-542be',
    storageBucket: 'wholesellexapplication-542be.firebasestorage.app',
    iosBundleId: 'com.example.wholeSelleXApplication',
  );
}
